# Generated by Django 5.2.6 on 2026-01-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_customer_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
    ]
