# Generated by Django 6.0.1 on 2026-05-06 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_item_name_ml_alter_customer_id_alter_expense_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='name_ml',
        ),
    ]
