# Generated by Django 6.0.1 on 2026-05-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_expenseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Google Pay', 'Google Pay'), ('Cash', 'Cash')], default='Google Pay', max_length=20),
        ),
    ]
