# Generated by Django 6.0.1 on 2026-06-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adjustment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='item_total',
            field=models.IntegerField(default=0),
        ),
    ]
